// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1FIt3eUe6DfnpfcSbWEnV6uS8sHqFVs',
    appId: '1:763201296420:web:9c0e38c7472601f80fe0b1',
    messagingSenderId: '763201296420',
    projectId: 'flutter-x-firebase01',
    authDomain: 'flutter-x-firebase01.firebaseapp.com',
    storageBucket: 'flutter-x-firebase01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxMXr6pcei6Q7kCiDgJ811VTGh9wb-WA',
    appId: '1:763201296420:android:f1d3c124cedf86fd0fe0b1',
    messagingSenderId: '763201296420',
    projectId: 'flutter-x-firebase01',
    storageBucket: 'flutter-x-firebase01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5LvjZM3iQXCna2uahp3CqoZpiBc1PpZ0',
    appId: '1:763201296420:ios:4e8e06852bfdb3560fe0b1',
    messagingSenderId: '763201296420',
    projectId: 'flutter-x-firebase01',
    storageBucket: 'flutter-x-firebase01.appspot.com',
    iosBundleId: 'com.example.newdigiration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5LvjZM3iQXCna2uahp3CqoZpiBc1PpZ0',
    appId: '1:763201296420:ios:4e8e06852bfdb3560fe0b1',
    messagingSenderId: '763201296420',
    projectId: 'flutter-x-firebase01',
    storageBucket: 'flutter-x-firebase01.appspot.com',
    iosBundleId: 'com.example.newdigiration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1FIt3eUe6DfnpfcSbWEnV6uS8sHqFVs',
    appId: '1:763201296420:web:4455c551d78ec3430fe0b1',
    messagingSenderId: '763201296420',
    projectId: 'flutter-x-firebase01',
    authDomain: 'flutter-x-firebase01.firebaseapp.com',
    storageBucket: 'flutter-x-firebase01.appspot.com',
  );
}
